[package]
name = "unused-pkg"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_toml = "0.20.2"
crates_io_api = "0.11.0"
package_json_schema = "0.2.1"
reqwest = "0.12.4"
semver = "1.0.23"
serde = "1.0.202"
serde_derive = "1.0.202"
walkdir = "2.5.0"
